# Site settings
title: Kaiya Xiong's Note
baseurl: ""
url: "https://note.azfs.com.cn"

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

theme: jekyll-theme-merlot